Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Beneficiary-Service, pull requests merged in 2024-10, with the labels that each got.

#46 Creacíón y ajuste para la entidad affiliate document
  src/affiliate-documents/affiliate-documents.controller.spec.ts
  src/affiliate-documents/affiliate-documents.controller.ts
  src/affiliate-documents/affiliate-documents.module.ts
  src/affiliate-documents/affiliate-documents.service.spec.ts
  src/affiliate-documents/affiliate-documents.service.ts
  src/affiliate-documents/dto/create-affiliate-document.dto.ts
  src/affiliate-documents/dto/update-affiliate-document.dto.ts
  src/affiliates/affiliates.module.ts
  src/affiliates/entities/affiliate-document.entity.ts
  src/affiliates/entities/affiliate.entity.ts
  src/app.module.ts
Labels: enhancement

#50 Creación de Entidad y relaciones de PersonAffiliate
  src/app.module.ts
  src/person_affiliate/entities/person_affiliate.entity.ts
  src/person_affiliate/person_affiliate.module.ts
  src/persons/entities/person.entity.ts
Labels: enhancement

#52 Obtener un afiliado por id
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.service.ts
Labels: enhancement

#53 Reestructuración de modulo person_affiliate
  src/affiliates/entities/affiliate.entity.ts
  src/app.module.ts
  src/person_affiliate/dto/create-person_affiliate.dto.ts
  src/person_affiliate/dto/update-person_affiliate.dto.ts
  src/person_affiliate/person_affiliate.module.ts
  src/persons/entities/person.entity.ts
  src/persons/entities/person_affiliate.entity.ts
  src/persons/person_affiliate.controller.ts
  src/persons/person_affiliate.service.ts
  src/persons/persons.module.ts
Labels: enhancement

#55 Configuracion para comunicacion del modulo afiliado a los demas microservicios y Re-exportación del Modulo
  src/affiliates/affiliates.module.ts
  src/affiliates/affiliates.service.ts
  src/affiliates/entities/affiliate-document.entity.ts
  src/affiliates/entities/affiliate-state.entity.ts
  src/affiliates/entities/affiliate.entity.ts
  src/affiliates/entities/index.ts
  src/affiliates/entities/state-type.entity.ts
  src/config/services.ts
  src/transports/nats.module.ts
Labels: enhancement

#58 Adición de variable booleana para identificar si la persona es afiliado
  src/persons/entities/person.entity.ts
  src/persons/persons.service.ts
Labels: enhancement

#60 Procedimiento para sacar los documentos de un afiliado entre microservicios v1
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.service.ts
  src/affiliates/entities/affiliate-document.entity.ts
  src/affiliates/entities/affiliate.entity.ts
Labels: enhancement

#61 Archivo Barril para entidades del modulo Persona
  src/affiliates/entities/affiliate.entity.ts
  src/persons/entities/index.ts
  src/persons/entities/person-affiliate.entity.ts
  src/persons/entities/person.entity.ts
  src/persons/persons.controller.spec.ts
  src/persons/persons.module.ts
  src/persons/persons.service.ts
Labels: enhancement

#62 API para desplegar la información del afiliado con su relación de personAffiliates
  src/persons/persons.controller.ts
  src/persons/persons.service.ts
Labels: enhancement

#64 función de retornar afiliado vinculado a una persona
  src/persons/persons.controller.ts
  src/persons/persons.service.ts
Labels: enhancement

#66 Desarrollo de End Point para Guardar Requisitos en el Nas mediante conexion FTP
  .env.template
  package.json
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.service.ts
  src/affiliates/dto/index.ts
  src/affiliates/pipes/file-required.pipe.ts
  src/config/envs.ts
  test/app.e2e-spec.ts
Labels: New

#67 Funcionalidad para devolver las relaciones de Person con PersonAffiliates
  src/persons/persons.service.ts
Labels: refactor

#68 Eliminación de controlador y servicio de PersonAffiliate
  src/persons/person_affiliate.controller.ts
  src/persons/person_affiliate.service.ts
  src/persons/persons.module.ts
Labels: invalid

#70 Creacion de Modulo FTP global para uso generico y ajuste de metodo para subir archivo
  package-lock.json
  package.json
  src/affiliates/affiliates.service.ts
  src/app.module.ts
  src/ftp/ftp.module.ts
  src/ftp/ftp.service.ts
Labels: enhancement

#71 Adición de nombres de los campos con Id's planos consumiendo servicios externos
  src/persons/persons.module.ts
  src/persons/persons.service.ts
Labels: enhancement

#74 Procedimiento para encontrar un documento especifico del afiliado
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.service.ts
  src/ftp/ftp.service.ts
Labels: New

#76 Creación de tablas y relaciones para registrar huellas
  src/persons/entities/fingerprint-type.entity.ts
  src/persons/entities/person-fingerprint.entity.ts
  src/persons/entities/person.entity.ts
Labels: enhancement

#77 Importación de entidades para Registro de huellas
  src/persons/entities/index.ts
  src/persons/persons.module.ts
Labels: enhancement

#80 Configuración para formatear con snakecode las modificaciones de la b…
  package.json
  src/app.module.ts
Labels: enhancement

#82 Procedimiento para mostrar datos del Afiliado
  .eslintrc.js
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.module.ts
  src/affiliates/affiliates.service.ts
  src/affiliates/entities/affiliate-state.entity.ts
  src/affiliates/entities/affiliate.entity.ts
  src/affiliates/entities/index.ts
  src/affiliates/entities/state-type.entity.ts
Labels: New

#83 bug cuando es null los data
  src/affiliates/affiliates.service.ts
  src/ftp/ftp.service.ts
Labels: bug

#85 Actualización para permitir seeders
  package-lock.json
  package.json
  src/app.module.ts
  src/database/data-source.ts
  src/database/database.module.ts
  src/database/seeds/1729535116092-create_fingerprints_types.ts
  src/persons/entities/fingerprint-type.entity.ts
  yarn.lock
Labels: enhancement

#88 Optimización de estructura de Metodos Globales
  package-lock.json
  src/affiliates/affiliates.module.ts
  src/app.module.ts
  src/common/common.module.ts
  src/common/ftp/ftp.service.ts
  src/common/index.ts
  src/common/nats/nats.service.ts
  src/common/pipes/file-required.pipe.ts
  src/ftp/ftp.module.ts
  src/main.ts
  src/persons/persons.module.ts
  src/transports/nats.module.ts
Labels: enhancement

#89 Mejora de Rutas para crear Documentos, Mostrar Informacion del afiliado y mostrar documentos
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.service.ts
Labels: enhancement

#90 ajuste de camelCase
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.service.ts
  src/affiliates/entities/affiliate-document.entity.ts
Labels: enhancement

#92 Servicio para poder ver obtener información de la persona con sus relaciones
  src/persons/entities/person-affiliate.entity.ts
  src/persons/entities/person.entity.ts
  src/persons/persons.service.ts
Labels: enhancement

#93 Adición de campo short_name a la tabla fingerprinttype
  src/persons/entities/fingerprint-type.entity.ts
Labels: enhancement

#94 camel case de entidad personFingerPrint
  src/persons/entities/person-fingerprint.entity.ts
Labels: refactor

#96 Creación de registros de la huellas por Persona
  src/persons/dto/create-person-fingerprint.dto.ts
  src/persons/dto/index.ts
  src/persons/persons.controller.ts
  src/persons/persons.service.ts
Labels: enhancement

#97 Ajuste a la respuesta para mostrar documentos del afiliado y avance para cotejar documentos
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.service.ts
Labels: bug

#98 Depliegue de registro de huellas registradas
  src/persons/persons.controller.ts
  src/persons/persons.service.ts
Labels: enhancement

#101 Actualización de seeder fingerprint_types
  src/database/seeds/1729535116092-create_fingerprints_types.ts
Labels: enhancement

#103 Procedimiento para Cotejar documentos del afiliado con los documentos requeridos del tramite y ajuste de insercion de shortened
  src/affiliates/affiliates.service.ts
Labels: enhancement, New

#104 Refactorización de registro de huellas
  src/persons/dto/create-person-fingerprint.dto.ts
  src/persons/persons.service.ts
Labels: refactor

#105 Desplegar el listado de huellas digitales
  src/persons/persons.controller.ts
  src/persons/persons.service.ts
Labels: enhancement
