Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Beneficiary-Service, pull requests merged in 2024-09, with the labels that each got.

#17 README para leventar el proyecto
  README.md
Labels: documentation

#18 Refactorización de persona
  src/persons/dto/create-person.dto.ts
  src/persons/entities/person.entity.ts
Labels: refactor

#20 Creación de Recursos de Persona
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.module.ts
  src/affiliates/affiliates.service.ts
  src/affiliates/dto/create-affiliate.dto.ts
  src/affiliates/dto/update-affiliate.dto.ts
  src/affiliates/entities/affiliate.entity.ts
  src/app.module.ts
Labels: enhancement

#22 Creación de la entidad afiliado
  src/affiliates/entities/affiliate.entity.ts
Labels: enhancement

#23 Cambios de api rest a microservicio
  package.json
  src/config/envs.ts
  src/config/index.ts
  src/config/services.ts
  src/main.ts
  src/persons/dto/create-person.dto.ts
  src/persons/dto/update-person.dto.ts
  src/persons/entities/person.entity.ts
  src/persons/persons.controller.ts
  src/persons/persons.service.ts
  yarn.lock
Labels: refactor

#24 Development
  .env.template
Labels: documentation

#25 Endpoint para desplegar toda la lista de Afiliados
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.service.ts
Labels: enhancement

#28 Creación de resource
  src/app.module.ts
  src/person_affiliate/dto/create-person_affiliate.dto.ts
  src/person_affiliate/dto/update-person_affiliate.dto.ts
  src/person_affiliate/entities/person_affiliate.entity.ts
  src/person_affiliate/person_affiliate.controller.ts
  src/person_affiliate/person_affiliate.module.ts
  src/person_affiliate/person_affiliate.service.ts
Labels: enhancement

#29 Añadidos pruebas unitarias en controlador de persona
  .env.template
  package.json
  src/common/dtos/pagination.dto.ts
  src/config/envs.ts
  src/persons/persons.controller.spec.ts
  src/persons/persons.controller.ts
  src/persons/persons.service.ts
  yarn.lock
Labels: enhancement

#30 merge de development a main
  .env.template
  package.json
  src/common/dtos/pagination.dto.ts
  src/config/envs.ts
  src/config/index.ts
  src/config/services.ts
  src/main.ts
  src/persons/dto/create-person.dto.ts
  src/persons/dto/update-person.dto.ts
  src/persons/entities/person.entity.ts
  src/persons/persons.controller.spec.ts
  src/persons/persons.controller.ts
  src/persons/persons.service.ts
  yarn.lock
Labels: enhancement

#34 Formateado de código para el modulo affiliate
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.module.ts
  src/affiliates/affiliates.service.ts
  src/affiliates/entities/affiliate.entity.ts
Labels: enhancement

#36 Formateado de código para el modulo person
  src/persons/dto/create-person.dto.ts
  src/persons/dto/update-person.dto.ts
  src/persons/entities/person.entity.ts
  src/persons/persons.controller.spec.ts
  src/persons/persons.module.ts
  src/persons/persons.service.ts
Labels: enhancement

#39 Formato de código de prettier
  .prettierrc
Labels: enhancement

#40 Formato de código para affiliatecontroller
  src/affiliates/affiliates.controller.ts
Labels: enhancement

#42 Filtros de búsqueda de persona
  src/persons/dto/filter-person.dto.ts
  src/persons/persons.controller.ts
  src/persons/persons.service.ts
Labels: enhancement

#43 Avance RESOURCE documentos del afiliado
  package.json
  src/affiliate-documents/affiliate-documents.controller.spec.ts
  src/affiliate-documents/affiliate-documents.controller.ts
  src/affiliate-documents/affiliate-documents.module.ts
  src/affiliate-documents/affiliate-documents.service.spec.ts
  src/affiliate-documents/affiliate-documents.service.ts
  src/affiliate-documents/dto/create-affiliate-document.dto.ts
  src/affiliate-documents/dto/update-affiliate-document.dto.ts
  src/affiliate-documents/entities/affiliate-document.entity.ts
  src/affiliates/entities/affiliate.entity.ts
  src/app.module.ts
  src/person_affiliate/entities/person_affiliate.entity.ts
Labels: New
