Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Beneficiary-Service, pull requests merged in 2025-01, with the labels that each got.

#129 Refactorización búsqueda de persona
  src/persons/persons.controller.ts
  src/persons/persons.service.ts
Labels: enhancement, refactor

#131 Procedimiento para ANALIZAR E IMPOTAR MASIVAMENTE DOCUMENTOS de los afiliados V1
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.service.ts
  src/common/ftp/ftp.service.ts
  src/database/seeds/1730293751153-import_requirements.ts
  src/main.ts
Labels: New

#132 Guardado de huellas tres por dedo registrando las de mejor calidad
  src/persons/persons.service.ts
Labels: enhancement, refactor

#134 Eliminación de la columna intentos
  src/database/migrations/1736952591955-create_column_attempts_personFingerprints.ts
  src/persons/entities/person-fingerprint.entity.ts
Labels: enhancement
